
import { TeamMember, CalendarEvent, RosterShift, Booking, StockItem, Supplier, MaintenanceTask, EntertainmentEvent, FunctionBooking, CashUpRecord, FileItem, LeaveRequest, Invoice, Recipe, IncidentReport, LostItem, TVScheduleItem, StocktakeSession, PurchaseOrder, TimePunch, BudgetTracker } from './types';
import { addDays, getStartOfWeek } from './utils';

// --- STAFF CONFIGURATION ---
// --- STAFF CONFIGURATION ---
export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'admin-nikko',
    name: 'Nikko',
    email: 'work.nikko@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    color: '#10B981',
    visible: true,
    role: 'Admin',
    pinCode: import.meta.env.VITE_ADMIN_PIN || '5551',
  },
  {
    id: 'foh-robert',
    name: 'Robert',
    avatar: '',
    color: '#EF4444',
    visible: true,
    role: 'Duty Manager',
    pinCode: '1001',
  },
  {
    id: 'foh-bianca',
    name: 'Bianca',
    avatar: '',
    color: '#F59E0B',
    visible: true,
    role: 'Duty Manager',
    pinCode: '1002',
  },
  {
    id: 'foh-nicole',
    name: 'Nicole',
    avatar: '',
    color: '#10B981',
    visible: true,
    role: 'Duty Manager',
    pinCode: '1003',
  },
  {
    id: 'foh-carma',
    name: 'Carma',
    avatar: '',
    color: '#EC4899',
    visible: true,
    role: 'Front of House',
    pinCode: '1005',
  },
  {
    id: 'foh-jess',
    name: 'Jess',
    avatar: '',
    color: '#8B5CF6',
    visible: true,
    role: 'Front of House',
    pinCode: '1006',
  },
  {
    id: 'foh-racheal',
    name: 'Racheal',
    avatar: '',
    color: '#14B8A6',
    visible: true,
    role: 'Front of House',
    pinCode: '1007',
  },
  {
    id: 'foh-harsh',
    name: 'Harsh',
    avatar: '',
    color: '#F43F5E',
    visible: true,
    role: 'Front of House',
    pinCode: '1008',
  },
];

// --- ROSTER GENERATION ---
const today = new Date();
const currentWeekStart = getStartOfWeek(today); // Returns Monday

export const INITIAL_SHIFTS: RosterShift[] = [];
export const INITIAL_LEAVE: LeaveRequest[] = [];

// --- OTHER INITIAL DATA ---

export const INITIAL_EVENTS: CalendarEvent[] = [];
export const INITIAL_BOOKINGS: Booking[] = [];

// --- RAW PRODUCT CSV DATA ---
const RAW_PRODUCT_CSV = `ProductID,ProductType,ProductGroup,ProductName,ProductName2,PriceBand,PriceGroup,VATRate,Measure,CostPricePerSKU,GrossSellPrice,BarCode,PLU,PLU2,SKUName,BINNumber,KPText,CommissionPercentage,AllowZeroPrice,UseStandardVAT,AwardCRMPoints,ChargePerMinute,ExcludeFromReceipt,PromptForDescription,SellByWeight,ServiceChargeExempt,PrintToKPStandalone,IsMain,ProductInfo,RezlynxCode,MeasureCostPricePerSKU,ProhibitSalesWhenUnderStocked,IsUseBatchSales,CookTimeSeconds,ShelfLifeSeconds,IsDisplayAfterProduced,IsBatchSalesProduceOnSale,AlcoholPercent,UnitVolume,AllowDiscount,ItemCookCount,SelfServiceFood,SelfServiceDrink,IsChooseLater,KP1,KP2,KP3,KP4,KP5,KP6,KP7,KP8,KP9,KP10,KP11,KP12,KP13,KP14,KP15,KP16,HideMeasureShortNameFromReceipt,ThirdPartyCRMPointsValue,ExtraReceiptText,CRMPointsValue,IsAvailableThroughTevalisAPI,IsAlcohol,CRMCode,ReportCategory,Region,Vintage,StockWarningLevel`;

export const INITIAL_SUPPLIERS: Supplier[] = [];

export const INITIAL_STOCK: StockItem[] = [
  {"id": "1816", "name": "Aperol", "category": "Aperitif", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1816", "name": "Aperol", "category": "Aperitif", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1817", "name": "Campari", "category": "Aperitif", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1817", "name": "Campari", "category": "Aperitif", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1818", "name": "Martini Rosso Vermouth", "category": "Aperitif", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1818", "name": "Martini Rosso Vermouth", "category": "Aperitif", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1819", "name": "Pimms", "category": "Aperitif", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1819", "name": "Pimms", "category": "Aperitif", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2003", "name": "Corona 0% BTL", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1622", "name": "Corona BTL", "category": "Beer", "quantity": 50, "unit": "Bottle Bucket", "minLevel": 1, "price": 35.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1622", "name": "Corona BTL", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 10, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1780", "name": "DB Draught Quart BTL", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2035", "name": "DB Quart", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1685", "name": "Emerson's Pilsner", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 1, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1779", "name": "Export Gold Quart BTL", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2002", "name": "Ginger Giant", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 1, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2043", "name": "Gordons Pink Gin TAP", "category": "Beer", "quantity": 50, "unit": "Glass", "minLevel": 1, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1689", "name": "Guinness", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 1, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1692", "name": "Kirin Hyoketsu Lemon", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 1, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1778", "name": "Lion Brown Quart BTL", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1690", "name": "Mac's Cloudy Apple Cider", "category": "Beer", "quantity": 50, "unit": "12oz", "minLevel": 1, "price": 9.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1690", "name": "Mac's Cloudy Apple Cider", "category": "Beer", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 22.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1690", "name": "Mac's Cloudy Apple Cider", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1683", "name": "Mac's Gold", "category": "Beer", "quantity": 50, "unit": "12oz", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1683", "name": "Mac's Gold", "category": "Beer", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 18.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1683", "name": "Mac's Gold", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1687", "name": "Panhead Pickup IPA", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 1, "price": 14.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2001", "name": "Panhead Sandman", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 1, "price": 14.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1688", "name": "Panhead Supercharger  APA", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 1, "price": 14.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1679", "name": "Speights Gold", "category": "Beer", "quantity": 50, "unit": "12oz", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1679", "name": "Speights Gold", "category": "Beer", "quantity": 50, "unit": "7oz", "minLevel": 10, "price": 5.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1679", "name": "Speights Gold", "category": "Beer", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 17.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1679", "name": "Speights Gold", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1680", "name": "Speights Mid Ale", "category": "Beer", "quantity": 50, "unit": "12oz", "minLevel": 1, "price": 9.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1680", "name": "Speights Mid Ale", "category": "Beer", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 16.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1680", "name": "Speights Mid Ale", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1624", "name": "Speights Old Dark BTL", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 9.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1776", "name": "Speights Quart BTL", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1626", "name": "Speights Summit 0% BTL", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 8.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1681", "name": "Speights Summit Ultra", "category": "Beer", "quantity": 50, "unit": "12oz", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1681", "name": "Speights Summit Ultra", "category": "Beer", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 17.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1681", "name": "Speights Summit Ultra", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1623", "name": "Speights Ultra Lime BTL", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 9.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1625", "name": "Steinlager 0% BTL", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 8.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1686", "name": "Steinlager Classic", "category": "Beer", "quantity": 50, "unit": "Jug", "minLevel": 1, "price": 19.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1686", "name": "Steinlager Classic", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2040", "name": "Steinlager Classic BTL", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 10.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1627", "name": "Steinlager Light 2.5% BTL", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 9.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1682", "name": "Steinlager Low Carb", "category": "Beer", "quantity": 50, "unit": "Jug", "minLevel": 1, "price": 18.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1682", "name": "Steinlager Low Carb", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1621", "name": "Steinlager Pure BTL", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 10.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1781", "name": "Steinlager Quart BTL", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 16.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1678", "name": "Stella Artois", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 1, "price": 14.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2260", "name": "Stella Artois BTL", "category": "Beer", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1777", "name": "Summit Quart BTL", "category": "Beer", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 14.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1691", "name": "Zeffer Hazy Lemonade", "category": "Beer", "quantity": 50, "unit": "Pint", "minLevel": 1, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1820", "name": "Early Times Old Reserve", "category": "Bourbon", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1820", "name": "Early Times Old Reserve", "category": "Bourbon", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1821", "name": "Gentleman Jack Tennessee Whiskey", "category": "Bourbon", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1821", "name": "Gentleman Jack Tennessee Whiskey", "category": "Bourbon", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1822", "name": "Jack Daniels Old No. 7", "category": "Bourbon", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1822", "name": "Jack Daniels Old No. 7", "category": "Bourbon", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1823", "name": "Jack Daniels Single Barrel Rye", "category": "Bourbon", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1823", "name": "Jack Daniels Single Barrel Rye", "category": "Bourbon", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1824", "name": "Jack Daniels Single Barrel Select", "category": "Bourbon", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1824", "name": "Jack Daniels Single Barrel Select", "category": "Bourbon", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1825", "name": "Jack Daniels Straight Rye", "category": "Bourbon", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1825", "name": "Jack Daniels Straight Rye", "category": "Bourbon", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1826", "name": "Jim Beam Honey Bourbon", "category": "Bourbon", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1826", "name": "Jim Beam Honey Bourbon", "category": "Bourbon", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1827", "name": "Jim Beam Small Batch", "category": "Bourbon", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1827", "name": "Jim Beam Small Batch", "category": "Bourbon", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1828", "name": "Jim Beam White Label", "category": "Bourbon", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1828", "name": "Jim Beam White Label", "category": "Bourbon", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1829", "name": "Knob Creek Small Batch 9yo", "category": "Bourbon", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1829", "name": "Knob Creek Small Batch 9yo", "category": "Bourbon", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1830", "name": "Makers Mark Kentucky", "category": "Bourbon", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1830", "name": "Makers Mark Kentucky", "category": "Bourbon", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1831", "name": "Southern Comfort", "category": "Bourbon", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1831", "name": "Southern Comfort", "category": "Bourbon", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1832", "name": "Wild Turkey Bourbon", "category": "Bourbon", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1832", "name": "Wild Turkey Bourbon", "category": "Bourbon", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1833", "name": "Chatelle Napoleon VSOP", "category": "Brandy/Cognac", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1833", "name": "Chatelle Napoleon VSOP", "category": "Brandy/Cognac", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2285", "name": " Frozen Strawberry Daiquiri", "category": "Cocktail/Shot/Shaker", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 15.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1645", "name": "Aperol Spritz", "category": "Cocktail/Shot/Shaker", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1648", "name": "Cosmopolitan", "category": "Cocktail/Shot/Shaker", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 15.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1647", "name": "Espresso Martini", "category": "Cocktail/Shot/Shaker", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 15.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2253", "name": "Fireball Cocktail $12", "category": "Cocktail/Shot/Shaker", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2254", "name": "Fireball Shot $10", "category": "Cocktail/Shot/Shaker", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 10.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2240", "name": "Firetini", "category": "Cocktail/Shot/Shaker", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2287", "name": "Fizzy Lizzy", "category": "Cocktail/Shot/Shaker", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 15.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2251", "name": "Jam Donut", "category": "Cocktail/Shot/Shaker", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1650", "name": "Long Island Iced Tea", "category": "Cocktail/Shot/Shaker", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 18.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1646", "name": "Margarita", "category": "Cocktail/Shot/Shaker", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 15.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1649", "name": "Mojito", "category": "Cocktail/Shot/Shaker", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 15.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2252", "name": "Quick F*ck", "category": "Cocktail/Shot/Shaker", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2286", "name": "Sex on the Beach", "category": "Cocktail/Shot/Shaker", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 15.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2244", "name": "Redbull & Jager", "category": "Cocktails", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 15.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2245", "name": "Redbull & Tequila", "category": "Cocktails", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 15.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2243", "name": "Redbull & Vodka", "category": "Cocktails", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 15.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1667", "name": "Cappuchino", "category": "Coffee", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 5.1, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1668", "name": "Chai Latte", "category": "Coffee", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 5.1, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1675", "name": "Earl Grey", "category": "Coffee", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 5.1, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1676", "name": "English Breakfast", "category": "Coffee", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 5.1, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1669", "name": "Flat White", "category": "Coffee", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 5.1, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1677", "name": "Green Tea", "category": "Coffee", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 5.1, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1674", "name": "Hot Chocolate", "category": "Coffee", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 5.1, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1670", "name": "Latte", "category": "Coffee", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 5.1, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1673", "name": "Long Black", "category": "Coffee", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 5.1, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1671", "name": "Mocha", "category": "Coffee", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 5.1, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1672", "name": "Short Black", "category": "Coffee", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 5.1, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1834", "name": "Bombay Sapphire London Dry Gin", "category": "Gin", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1834", "name": "Bombay Sapphire London Dry Gin", "category": "Gin", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1835", "name": "Four Pillars Bloody Shiraz Gin", "category": "Gin", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 10.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1835", "name": "Four Pillars Bloody Shiraz Gin", "category": "Gin", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1836", "name": "Four Pillars Fresh Yuzu Gin", "category": "Gin", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 10.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1836", "name": "Four Pillars Fresh Yuzu Gin", "category": "Gin", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1837", "name": "Four Pillars Rare Dry Gin", "category": "Gin", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 10.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1837", "name": "Four Pillars Rare Dry Gin", "category": "Gin", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1838", "name": "Gordons London Dry Gin", "category": "Gin", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1838", "name": "Gordons London Dry Gin", "category": "Gin", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1839", "name": "Gordons London Pink Gin", "category": "Gin", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1839", "name": "Gordons London Pink Gin", "category": "Gin", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1840", "name": "Hendricks", "category": "Gin", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1840", "name": "Hendricks", "category": "Gin", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1841", "name": "Rogue Society Gin", "category": "Gin", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1841", "name": "Rogue Society Gin", "category": "Gin", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1842", "name": "Roku Japanese", "category": "Gin", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1842", "name": "Roku Japanese", "category": "Gin", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1843", "name": "Scapegrace Classic Premium Dry Gin", "category": "Gin", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1843", "name": "Scapegrace Classic Premium Dry Gin", "category": "Gin", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1844", "name": "Tanqueray", "category": "Gin", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1844", "name": "Tanqueray", "category": "Gin", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1001", "name": "Open Drink", "category": "Misc Drinks", "quantity": 50, "unit": "Each", "minLevel": 0, "price": 0.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1651", "name": "Apple Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Glass", "minLevel": 1, "price": 5.7, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1651", "name": "Apple Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 10.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1651", "name": "Apple Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Kids", "minLevel": 10, "price": 4.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1651", "name": "Apple Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 6.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2288", "name": "Cloverless Sour (Non Alcoholic)", "category": "Non Alcoholic", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 15.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1656", "name": "Coca-Cola Classic", "category": "Non Alcoholic", "quantity": 50, "unit": "Glass", "minLevel": 1, "price": 4.6, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1656", "name": "Coca-Cola Classic", "category": "Non Alcoholic", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 8.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1656", "name": "Coca-Cola Classic", "category": "Non Alcoholic", "quantity": 50, "unit": "Kids", "minLevel": 10, "price": 4.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1656", "name": "Coca-Cola Classic", "category": "Non Alcoholic", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 5.7, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1657", "name": "Coca-Cola No Sugar", "category": "Non Alcoholic", "quantity": 50, "unit": "Glass", "minLevel": 1, "price": 4.6, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1657", "name": "Coca-Cola No Sugar", "category": "Non Alcoholic", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 8.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1657", "name": "Coca-Cola No Sugar", "category": "Non Alcoholic", "quantity": 50, "unit": "Kids", "minLevel": 10, "price": 4.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1657", "name": "Coca-Cola No Sugar", "category": "Non Alcoholic", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 5.7, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1652", "name": "Cranberry Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Glass", "minLevel": 1, "price": 5.7, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1652", "name": "Cranberry Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 10.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1652", "name": "Cranberry Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Kids", "minLevel": 10, "price": 4.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1652", "name": "Cranberry Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 6.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1660", "name": "Ginger Ale", "category": "Non Alcoholic", "quantity": 50, "unit": "Glass", "minLevel": 1, "price": 4.6, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1660", "name": "Ginger Ale", "category": "Non Alcoholic", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 8.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1660", "name": "Ginger Ale", "category": "Non Alcoholic", "quantity": 50, "unit": "Kids", "minLevel": 10, "price": 4.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1660", "name": "Ginger Ale", "category": "Non Alcoholic", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 5.7, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1664", "name": "Ginger Beer (330ml)", "category": "Non Alcoholic", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 5.7, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1661", "name": "Indian Tonic Water", "category": "Non Alcoholic", "quantity": 50, "unit": "Glass", "minLevel": 1, "price": 4.6, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1661", "name": "Indian Tonic Water", "category": "Non Alcoholic", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 8.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1661", "name": "Indian Tonic Water", "category": "Non Alcoholic", "quantity": 50, "unit": "Kids", "minLevel": 10, "price": 4.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1661", "name": "Indian Tonic Water", "category": "Non Alcoholic", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 5.7, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1658", "name": "L&P", "category": "Non Alcoholic", "quantity": 50, "unit": "Glass", "minLevel": 1, "price": 4.6, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1658", "name": "L&P", "category": "Non Alcoholic", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 8.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1658", "name": "L&P", "category": "Non Alcoholic", "quantity": 50, "unit": "Kids", "minLevel": 10, "price": 4.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1658", "name": "L&P", "category": "Non Alcoholic", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 5.7, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1662", "name": "Lemon, Lime & Bitters", "category": "Non Alcoholic", "quantity": 50, "unit": "Glass", "minLevel": 1, "price": 5.1, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1662", "name": "Lemon, Lime & Bitters", "category": "Non Alcoholic", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 10.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1662", "name": "Lemon, Lime & Bitters", "category": "Non Alcoholic", "quantity": 50, "unit": "Kids", "minLevel": 10, "price": 4.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1662", "name": "Lemon, Lime & Bitters", "category": "Non Alcoholic", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 6.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1659", "name": "Lemonade", "category": "Non Alcoholic", "quantity": 50, "unit": "Glass", "minLevel": 1, "price": 4.6, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1659", "name": "Lemonade", "category": "Non Alcoholic", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 8.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1659", "name": "Lemonade", "category": "Non Alcoholic", "quantity": 50, "unit": "Kids", "minLevel": 10, "price": 4.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1659", "name": "Lemonade", "category": "Non Alcoholic", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 5.7, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1653", "name": "Orange Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Glass", "minLevel": 1, "price": 5.7, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1653", "name": "Orange Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 10.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1653", "name": "Orange Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Kids", "minLevel": 10, "price": 4.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1653", "name": "Orange Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 6.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1654", "name": "Pineapple Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Glass", "minLevel": 1, "price": 5.7, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1654", "name": "Pineapple Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 10.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1654", "name": "Pineapple Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Kids", "minLevel": 10, "price": 4.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1654", "name": "Pineapple Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 6.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2044", "name": "Rasp ", "category": "Non Alcoholic", "quantity": 50, "unit": "No Measure", "minLevel": 0, "price": 0.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2045", "name": "Rasp Cordial ", "category": "Non Alcoholic", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 0.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1663", "name": "Redbull Can (200ml)", "category": "Non Alcoholic", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 6.7, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2262", "name": "Soda Water", "category": "Non Alcoholic", "quantity": 50, "unit": "Glass", "minLevel": 1, "price": -1.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2262", "name": "Soda Water", "category": "Non Alcoholic", "quantity": 50, "unit": "Kids", "minLevel": 10, "price": -1.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2262", "name": "Soda Water", "category": "Non Alcoholic", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": -1.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2264", "name": "Sprite Zero", "category": "Non Alcoholic", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 5.7, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1655", "name": "Tomato Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Glass", "minLevel": 1, "price": 5.7, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1655", "name": "Tomato Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": 10.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1655", "name": "Tomato Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Kids", "minLevel": 10, "price": 4.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1655", "name": "Tomato Juice", "category": "Non Alcoholic", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": 6.2, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1666", "name": "Voyager Water Sparkling", "category": "Non Alcoholic", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 10.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1665", "name": "Voyager Water Still", "category": "Non Alcoholic", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 10.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2263", "name": "Water", "category": "Non Alcoholic", "quantity": 50, "unit": "Glass", "minLevel": 1, "price": -1.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2263", "name": "Water", "category": "Non Alcoholic", "quantity": 50, "unit": "Jug", "minLevel": 10, "price": -1.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2263", "name": "Water", "category": "Non Alcoholic", "quantity": 50, "unit": "Kids", "minLevel": 10, "price": -1.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2263", "name": "Water", "category": "Non Alcoholic", "quantity": 50, "unit": "Pint", "minLevel": 10, "price": -1.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1845", "name": "Agavero Tequila Liqueur", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1845", "name": "Agavero Tequila Liqueur", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1846", "name": "Baileys Irish Cream", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1846", "name": "Baileys Irish Cream", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1847", "name": "Bols Triple Sec", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 10.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1847", "name": "Bols Triple Sec", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1848", "name": "Chambord", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1848", "name": "Chambord", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1849", "name": "Cointreau", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1849", "name": "Cointreau", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1850", "name": "De Kuyper Blue Curacao", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1850", "name": "De Kuyper Blue Curacao", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1851", "name": "De Kyuper Butterschotch Schnapps", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1851", "name": "De Kyuper Butterschotch Schnapps", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1852", "name": "De Kyuper Peach Schnapps", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1852", "name": "De Kyuper Peach Schnapps", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1853", "name": "Drambuie", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1853", "name": "Drambuie", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1854", "name": "Fireball Cinnamon Whisky", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1854", "name": "Fireball Cinnamon Whisky", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1855", "name": "Frangelico Hazelunt", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1855", "name": "Frangelico Hazelunt", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1856", "name": "Galliano Black Sambucca", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1856", "name": "Galliano Black Sambucca", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1857", "name": "Galliano Vanilla", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1857", "name": "Galliano Vanilla", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1858", "name": "Galliano White Sambucca", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1858", "name": "Galliano White Sambucca", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1859", "name": "Glayva Scotch", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1859", "name": "Glayva Scotch", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1860", "name": "Jagermeister", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1860", "name": "Jagermeister", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1861", "name": "Kahlua", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1861", "name": "Kahlua", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1862", "name": "Malibu", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1862", "name": "Malibu", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1863", "name": "Midori", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1863", "name": "Midori", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1864", "name": "Ouzo 12", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1864", "name": "Ouzo 12", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2283", "name": "Shankey's Whip", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2283", "name": "Shankey's Whip", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1865", "name": "St Germain Elderflower", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1865", "name": "St Germain Elderflower", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1866", "name": "Stones Green Ginger Wine", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1866", "name": "Stones Green Ginger Wine", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1867", "name": "Tia Maria", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1867", "name": "Tia Maria", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1868", "name": "Wild Turkey American Honey", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 10.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1868", "name": "Wild Turkey American Honey", "category": "Other Spirits / Liquers", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2031", "name": "Cabernet Sauvignon", "category": "Red Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 52.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2031", "name": "Cabernet Sauvignon", "category": "Red Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 18.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2031", "name": "Cabernet Sauvignon", "category": "Red Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1643", "name": "Elefante 'El Valiente Tempranillo", "category": "Red Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 60.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1643", "name": "Elefante 'El Valiente Tempranillo", "category": "Red Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 20.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1643", "name": "Elefante 'El Valiente Tempranillo", "category": "Red Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2029", "name": "House Red Merlot Kopiko Bay", "category": "Red Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 38.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2029", "name": "House Red Merlot Kopiko Bay", "category": "Red Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2029", "name": "House Red Merlot Kopiko Bay", "category": "Red Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 10.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2026", "name": "Huntaway Reserve Pinot Noir", "category": "Red Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 54.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2026", "name": "Huntaway Reserve Pinot Noir", "category": "Red Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 18.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2026", "name": "Huntaway Reserve Pinot Noir", "category": "Red Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1642", "name": "Kopiko Bay Merlot", "category": "Red Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 65.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1642", "name": "Kopiko Bay Merlot", "category": "Red Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 21.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1642", "name": "Kopiko Bay Merlot", "category": "Red Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1644", "name": "Little Giant Shiraz", "category": "Red Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 70.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1644", "name": "Little Giant Shiraz", "category": "Red Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 24.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1644", "name": "Little Giant Shiraz", "category": "Red Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2030", "name": "Merlot", "category": "Red Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 50.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2030", "name": "Merlot", "category": "Red Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 17.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2030", "name": "Merlot", "category": "Red Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2028", "name": "Mt Difficulty Estate Bannockburn", "category": "Red Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 88.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1640", "name": "Rebel Pinot Noir", "category": "Red Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 49.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1640", "name": "Rebel Pinot Noir", "category": "Red Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 16.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1640", "name": "Rebel Pinot Noir", "category": "Red Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2027", "name": "Roaring Meg Pinot Noir", "category": "Red Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 64.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2027", "name": "Roaring Meg Pinot Noir", "category": "Red Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 21.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2027", "name": "Roaring Meg Pinot Noir", "category": "Red Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1641", "name": "Rose & Rose Pinot Noir", "category": "Red Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 65.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1641", "name": "Rose & Rose Pinot Noir", "category": "Red Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 21.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1641", "name": "Rose & Rose Pinot Noir", "category": "Red Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2032", "name": "Shiraz", "category": "Red Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 54.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2032", "name": "Shiraz", "category": "Red Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 18.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2032", "name": "Shiraz", "category": "Red Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2033", "name": "Taylors 10 Year Tawny Port", "category": "Red Wine", "quantity": 50, "unit": "Small", "minLevel": 1, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1908", "name": "Canadian Club & Coke RTD", "category": "RTD", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1906", "name": "Coruba & Coke RTD", "category": "RTD", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1904", "name": "Gordons Gin & Tonic RTD", "category": "RTD", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1903", "name": "Gordons Pink Gin RTD", "category": "RTD", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1905", "name": "Jack Daniels & Coke RTD", "category": "RTD", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1901", "name": "Jim Beam & Coke RTD", "category": "RTD", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1902", "name": "Kirin Hyoketsyu RTD", "category": "RTD", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1907", "name": "Smirnoff RTD", "category": "RTD", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1869", "name": "Appleton Estate Signature Blend", "category": "Rum", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1869", "name": "Appleton Estate Signature Blend", "category": "Rum", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1870", "name": "Bacardi Carta Blanca", "category": "Rum", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 8.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1870", "name": "Bacardi Carta Blanca", "category": "Rum", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1871", "name": "Bacardi Carta Oro", "category": "Rum", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1871", "name": "Bacardi Carta Oro", "category": "Rum", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1872", "name": "Bacardi Ocho 8yo", "category": "Rum", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1872", "name": "Bacardi Ocho 8yo", "category": "Rum", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1873", "name": "Bacardi Spiced", "category": "Rum", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1873", "name": "Bacardi Spiced", "category": "Rum", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1874", "name": "Coruba", "category": "Rum", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1874", "name": "Coruba", "category": "Rum", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1875", "name": "Helmsman White Rum", "category": "Rum", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1875", "name": "Helmsman White Rum", "category": "Rum", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1876", "name": "Sailor Jerry Spiced Rum", "category": "Rum", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1876", "name": "Sailor Jerry Spiced Rum", "category": "Rum", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1877", "name": "The Kraken Spiced Rum", "category": "Rum", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1877", "name": "The Kraken Spiced Rum", "category": "Rum", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1878", "name": "Famous Grouse Scotch Whiskey", "category": "Scotch", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1878", "name": "Famous Grouse Scotch Whiskey", "category": "Scotch", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1879", "name": "Glenfiddich 12yo Single Malt", "category": "Scotch", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 10.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1879", "name": "Glenfiddich 12yo Single Malt", "category": "Scotch", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1880", "name": "Johnnie Walker Black Label", "category": "Scotch", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1880", "name": "Johnnie Walker Black Label", "category": "Scotch", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 15.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1881", "name": "Johnnie Walker Blue Label", "category": "Scotch", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 17.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1881", "name": "Johnnie Walker Blue Label", "category": "Scotch", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 26.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1882", "name": "Johnnie Walker Green Label", "category": "Scotch", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 17.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1882", "name": "Johnnie Walker Green Label", "category": "Scotch", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 26.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1883", "name": "Johnnie Walker Red Label", "category": "Scotch", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 10.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1883", "name": "Johnnie Walker Red Label", "category": "Scotch", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1884", "name": "Laphroaig 10yo", "category": "Scotch", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1884", "name": "Laphroaig 10yo", "category": "Scotch", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 15.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1885", "name": "Talisker 10yo", "category": "Scotch", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1885", "name": "Talisker 10yo", "category": "Scotch", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 15.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1886", "name": "Jose Cuervo Agavero", "category": "Tequila", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1886", "name": "Jose Cuervo Agavero", "category": "Tequila", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1887", "name": "Jose Cuervo Gold Especial", "category": "Tequila", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1887", "name": "Jose Cuervo Gold Especial", "category": "Tequila", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1888", "name": "Jose Cuervo Tradicional Reposado", "category": "Tequila", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1888", "name": "Jose Cuervo Tradicional Reposado", "category": "Tequila", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1889", "name": "Patron Silver", "category": "Tequila", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1889", "name": "Patron Silver", "category": "Tequila", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1890", "name": "Absolut Vanilla", "category": "Vodka", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1890", "name": "Absolut Vanilla", "category": "Vodka", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1891", "name": "Absolut Vodka", "category": "Vodka", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1891", "name": "Absolut Vodka", "category": "Vodka", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1893", "name": "Grey Goose", "category": "Vodka", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 10.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1893", "name": "Grey Goose", "category": "Vodka", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1894", "name": "Ketel One Vodka", "category": "Vodka", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1894", "name": "Ketel One Vodka", "category": "Vodka", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1895", "name": "Rogue Society Vodka", "category": "Vodka", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1895", "name": "Rogue Society Vodka", "category": "Vodka", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1896", "name": "Scapegrace Vodka", "category": "Vodka", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1896", "name": "Scapegrace Vodka", "category": "Vodka", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1897", "name": "Smirnoff Red", "category": "Vodka", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1897", "name": "Smirnoff Red", "category": "Vodka", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1898", "name": "Bushmills 10yo Irish", "category": "Whiskey", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1898", "name": "Bushmills 10yo Irish", "category": "Whiskey", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1899", "name": "Canadian Club", "category": "Whiskey", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 9.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1899", "name": "Canadian Club", "category": "Whiskey", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2267", "name": "Crown Royal Whisky", "category": "Whiskey", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 11.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2267", "name": "Crown Royal Whisky", "category": "Whiskey", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1900", "name": "Jameson Irish", "category": "Whiskey", "quantity": 50, "unit": "15ml", "minLevel": 1, "price": 10.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1900", "name": "Jameson Irish", "category": "Whiskey", "quantity": 50, "unit": "30ml", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1629", "name": "Cloudy Bay Pelorus NV", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 75.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1629", "name": "Cloudy Bay Pelorus NV", "category": "White Wine", "quantity": 50, "unit": "Glass", "minLevel": 10, "price": 16.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2011", "name": "Daniel Le Brun", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 72.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1639", "name": "Duck Hunter Stiletto Ranch", "category": "White Wine", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 70.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1637", "name": "Edenvale Sauvignon Blanc - Alcohol Removed", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 39.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1637", "name": "Edenvale Sauvignon Blanc - Alcohol Removed", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 14.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1637", "name": "Edenvale Sauvignon Blanc - Alcohol Removed", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 8.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2016", "name": "House Chard Kopiko Bay", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 38.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2016", "name": "House Chard Kopiko Bay", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2016", "name": "House Chard Kopiko Bay", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 10.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2036", "name": "House Pinot Gris Kopiko Bay", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 38.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2036", "name": "House Pinot Gris Kopiko Bay", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2036", "name": "House Pinot Gris Kopiko Bay", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 10.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2012", "name": "House Sav Kopiko Bay", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 38.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2012", "name": "House Sav Kopiko Bay", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2012", "name": "House Sav Kopiko Bay", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 10.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2018", "name": "Huntaway Reserve Chard", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 54.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2018", "name": "Huntaway Reserve Chard", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 18.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2018", "name": "Huntaway Reserve Chard", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2008", "name": "Lindauer Brut Cuvee", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 44.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2008", "name": "Lindauer Brut Cuvee", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2006", "name": "Lindauer Fraise", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 44.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2006", "name": "Lindauer Fraise", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2009", "name": "Lindauer Prosecco", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 58.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2009", "name": "Lindauer Prosecco", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 15.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2007", "name": "Lindauer Sauv Blanc", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 44.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2007", "name": "Lindauer Sauv Blanc", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1634", "name": "Mandoleto Pinot Grigio", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 60.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1634", "name": "Mandoleto Pinot Grigio", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 20.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1634", "name": "Mandoleto Pinot Grigio", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1630", "name": "Moet & Chandon Imperial Brut NV", "category": "White Wine", "quantity": 50, "unit": "Each", "minLevel": 1, "price": 131.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1632", "name": "Petal & Stem Sauvignon Blanc", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 65.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1632", "name": "Petal & Stem Sauvignon Blanc", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 21.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1632", "name": "Petal & Stem Sauvignon Blanc", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1633", "name": "Rebel Pinot Gris", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 49.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1633", "name": "Rebel Pinot Gris", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 16.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1633", "name": "Rebel Pinot Gris", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1638", "name": "Rebel Rose", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 49.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1638", "name": "Rebel Rose", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 16.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1638", "name": "Rebel Rose", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1631", "name": "Rebel Sauvignon Blanc", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 49.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1631", "name": "Rebel Sauvignon Blanc", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 16.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1631", "name": "Rebel Sauvignon Blanc", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 11.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2022", "name": "Roaring Meg PG", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 56.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2022", "name": "Roaring Meg PG", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 19.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2022", "name": "Roaring Meg PG", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2034", "name": "Roaring Meg Riesling", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 56.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2034", "name": "Roaring Meg Riesling", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 19.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2034", "name": "Roaring Meg Riesling", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 13.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2010", "name": "Summer Love", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 58.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2010", "name": "Summer Love", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1628", "name": "The Hare & Tortoise Prosecco NV", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 60.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1628", "name": "The Hare & Tortoise Prosecco NV", "category": "White Wine", "quantity": 50, "unit": "Glass", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2017", "name": "The Ned Chard", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 54.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2017", "name": "The Ned Chard", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 18.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2017", "name": "The Ned Chard", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2021", "name": "The Ned PG", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 54.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2021", "name": "The Ned PG", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 18.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2021", "name": "The Ned PG", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2024", "name": "The Ned Pinot Rose", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 52.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2024", "name": "The Ned Pinot Rose", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 18.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2024", "name": "The Ned Pinot Rose", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2015", "name": "The Ned Sav", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 54.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2015", "name": "The Ned Sav", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 18.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2015", "name": "The Ned Sav", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 13.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1635", "name": "Torea Chardonnay", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 60.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1635", "name": "Torea Chardonnay", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 20.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1635", "name": "Torea Chardonnay", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1636", "name": "Waipara Hills Chardonnay", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 70.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1636", "name": "Waipara Hills Chardonnay", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 24.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "1636", "name": "Waipara Hills Chardonnay", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 14.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2019", "name": "Wither Hills Early Light PG 9.5%", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 48.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2019", "name": "Wither Hills Early Light PG 9.5%", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 16.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2019", "name": "Wither Hills Early Light PG 9.5%", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2013", "name": "Wither Hills Early Light Sav 9.5%", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 48.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2013", "name": "Wither Hills Early Light Sav 9.5%", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 16.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2013", "name": "Wither Hills Early Light Sav 9.5%", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2020", "name": "Wither Hills PG", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 50.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2020", "name": "Wither Hills PG", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 17.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2020", "name": "Wither Hills PG", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2025", "name": "Wither Hills Riesling", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 50.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2025", "name": "Wither Hills Riesling", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 16.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2025", "name": "Wither Hills Riesling", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2023", "name": "Wither Hills Rose", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 50.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2023", "name": "Wither Hills Rose", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 16.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2023", "name": "Wither Hills Rose", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 12.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2014", "name": "Wither Hills Sav", "category": "White Wine", "quantity": 50, "unit": "Bottle", "minLevel": 1, "price": 50.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2014", "name": "Wither Hills Sav", "category": "White Wine", "quantity": 50, "unit": "Large", "minLevel": 10, "price": 17.0, "cost": 0.0, "productType": "Beverage", "isDemo": false},
  {"id": "2014", "name": "Wither Hills Sav", "category": "White Wine", "quantity": 50, "unit": "Small", "minLevel": 10, "price": 12.5, "cost": 0.0, "productType": "Beverage", "isDemo": false},
];
export const INITIAL_MAINTENANCE: MaintenanceTask[] = [];
export const INITIAL_ENTERTAINMENT: EntertainmentEvent[] = [];
export const INITIAL_FUNCTIONS: FunctionBooking[] = [];
export const INITIAL_FINANCE: CashUpRecord[] = [];
export const INITIAL_INVOICES: Invoice[] = [];
export const INITIAL_RECIPES: Recipe[] = [];
export const INITIAL_INCIDENTS: IncidentReport[] = [];
export const INITIAL_LOST_FOUND: LostItem[] = [];
export const INITIAL_TV_SCHEDULE: TVScheduleItem[] = [];
export const INITIAL_STOCKTAKES: StocktakeSession[] = [];

export const INITIAL_ORDERS: any[] = [];
export const INITIAL_TIME_PUNCHES: any[] = [];
export const INITIAL_BUDGETS: any[] = [];
export const SOCIAL_LINKS = [];
export const HOURS: number[] = Array.from({ length: 24 }, (_, i) => i);
export const INITIAL_FILES: any[] = [];
